% function T = sc54(n, gridx, amidx, extx, coefs)
%
% returns the matrix of the 1D quintic spline collocation linear system
% with general boundary conditions and general linear 4th order DE operator
% on a general grid
% amidx is dummy argument, at least for fourth order problems

function T = sc54(n, gridx, amidx, extx, coefs)

numeq = n+5;
T = sppentad(1, 1, 1, 1, 1, numeq);

i = 1; px = gridx(1); ip = i;
bspl = bsplvd(extx, 6, px, ip+5);
T(i, 1:5) = (bspl(1:5, 1))'*coefs(i, 1) ...
          + (bspl(1:5, 2))'*coefs(i, 2) ...
          + (bspl(1:5, 3))'*coefs(i, 3) ...
          + (bspl(1:5, 4))'*coefs(i, 4) ...
          + (bspl(1:5, 5))'*coefs(i, 5);
i = i+1;
T(i, 1:5) = (bspl(1:5, 1))'*coefs(i, 1) ...
          + (bspl(1:5, 2))'*coefs(i, 2) ...
          + (bspl(1:5, 3))'*coefs(i, 3) ...
          + (bspl(1:5, 4))'*coefs(i, 4) ...
          + (bspl(1:5, 5))'*coefs(i, 5);
for i = 3:n+3
    px = gridx(i-2); ip = i-2;
    bspl = bsplvd(extx, 6, px, ip+5);
%   T(i, i-2:i+2) = (bspl(1:5, 1))';         % Interpolation
    T(i, i-2:i+2) = (bspl(1:5, 1))'*coefs(i, 1) ...
                  + (bspl(1:5, 2))'*coefs(i, 2) ...
                  + (bspl(1:5, 3))'*coefs(i, 3) ...
                  + (bspl(1:5, 4))'*coefs(i, 4) ...
                  + (bspl(1:5, 5))'*coefs(i, 5);
end
i = n+4; px = gridx(n+1); ip = i-3;
bspl = bsplvd(extx, 6, px, ip+5);
T(numeq-1, numeq-4:numeq) = (bspl(1:5, 1))'*coefs(i, 1) ...
                          + (bspl(1:5, 2))'*coefs(i, 2) ...
                          + (bspl(1:5, 3))'*coefs(i, 3) ...
                          + (bspl(1:5, 4))'*coefs(i, 4) ...
                          + (bspl(1:5, 5))'*coefs(i, 5);
i = i+1;
T(numeq, numeq-4:numeq) = (bspl(1:5, 1))'*coefs(i, 1) ...
                        + (bspl(1:5, 2))'*coefs(i, 2) ...
                        + (bspl(1:5, 3))'*coefs(i, 3) ...
                        + (bspl(1:5, 4))'*coefs(i, 4) ...
                        + (bspl(1:5, 5))'*coefs(i, 5);
